[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
toml = "=0.8.19"
regex = "1.11.1"
walkdir = "2.5.0"
itertools = "0.13.0"
hashbrown = "0.15"