[[test_cases]]
input = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""
output = "14"

[[test_cases]]
input = """
..0
.0.
...
"""
output = "1"
